version: "3.8"

services:
  cloudflared:
    container_name: cloudflared
    # Restart on crashes and on reboots
    restart: always
    image: erisamoe/cloudflared:latest
    command: proxy-dns
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query"

      # Listen on an unprivileged port
      - "TUNNEL_DNS_PORT=${CLOUDFLARED_PORT}"

      # Listen on all interfaces
      - "TUNNEL_DNS_ADDRESS=0.0.0.0"

    # Attach cloudflared only to the private network
    networks:
      internal:
        # Internal IP of the cloudflared container
        ipv4_address: ${CLOUDFLARED_INTERNAL_IP}

networks:
  # Create the internal network
  internal:
    ipam:
      config:
        ## subnet of the internal network
        - subnet: ${INTERNAL_SUBNET}

  # The priv_lan network is already set up, so it is an 'external' network
  priv_lan:
    external:
      name: priv_lan
